# M12-L1 Problem 2

Sometimes the dimensionality is greater than the number of samples. For example,in this problem X has 19 features, but there are only 4 data points. You will need to use the alternate PCA formulation in this case. Follow the steps in the cells below to implement this method.

In [11]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([  [-2,  1,  2, -3,  4,  1,  0,  3,  0,  2,  1,  1,  2,  3, -2, -3, 2,  1,  0],
                [ 1,  2, -4,  2, -4,  2,  5,  2,  2,  1, -3,  0,  0,  1, -2,  1, 1, -3, -2],
                [ 1, -3,  2,  1,  0, -3, -5, -1,  3,  3, -2, -3, -2, -1,  1,  0, 5,  4,  2],
                [ 3, -1,  0,  2,  2, -5, -4, -1,  2, -1,  3,  4,  4,  2,  1,  2, -2,  1, -1]])


## Computing Principal Components

### The A matrix

First, you should compute the `A` matrix, where A is $(X-\mu)'$. (Note the transpose)

Print this matrix below. It should have size $19\times 4$.

In [13]:
# YOUR CODE GOES HERE
mu = np.mean(X, axis=0)
X_centered = X - mu
A = X_centered.T
print("A = \n", A)

A = 
 [[-2.75  0.25  0.25  2.25]
 [ 1.25  2.25 -2.75 -0.75]
 [ 2.   -4.    2.    0.  ]
 [-3.5   1.5   0.5   1.5 ]
 [ 3.5  -4.5  -0.5   1.5 ]
 [ 2.25  3.25 -1.75 -3.75]
 [ 1.    6.   -4.   -3.  ]
 [ 2.25  1.25 -1.75 -1.75]
 [-1.75  0.25  1.25  0.25]
 [ 0.75 -0.25  1.75 -2.25]
 [ 1.25 -2.75 -1.75  3.25]
 [ 0.5  -0.5  -3.5   3.5 ]
 [ 1.   -1.   -3.    3.  ]
 [ 1.75 -0.25 -2.25  0.75]
 [-1.5  -1.5   1.5   1.5 ]
 [-3.    1.    0.    2.  ]
 [ 0.5  -0.5   3.5  -3.5 ]
 [ 0.25 -3.75  3.25  0.25]
 [ 0.25 -1.75  2.25 -0.75]]


### "Small" covariance matrix

By transposing $X-\mu$ to get $A$, now we can compute a smaller covariance matrix with $A' A$. Compute this matrix, `C`, below and print the result.

In [14]:
# YOUR CODE GOES HERE
n = A.shape[0]
C = (1 / (n - 1)) * np.dot(A.T, A)
print("C = \n", C)

C = 
 [[ 3.88194444 -1.04861111 -1.46527778 -1.36805556]
 [-1.04861111  6.74305556 -2.95138889 -2.74305556]
 [-1.46527778 -2.95138889  5.46527778 -1.04861111]
 [-1.36805556 -2.74305556 -1.04861111  5.15972222]]


### Finding nonzero eigenvectors
Next, find the useful (nonzero) eigenvectors of `C`. 

For validation purposes, there should be 3 useful eigenvectors, and the first one is `[-0.06628148 -0.79038331 0.47285044 0.38381435]`. 

Keep these eigenvectors in a $4\times 3$ array `e`.

In [21]:
# YOUR CODE GOES HERE
eigenvalues, eigenvectors = np.linalg.eig(C)

sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

e = eigenvectors[:, :-1]
print("Eigenvectors, e:\n", e)

Eigenvectors, e:
 [[-0.06628148  0.04124587 -0.86249959]
 [-0.79038331 -0.06822502  0.34733208]
 [ 0.47285044 -0.69123739  0.22046165]
 [ 0.38381435  0.71821654  0.29470586]]


### Calculating "eigenfaces"

Now, we have all we need to compute `U`, the matrix of eigenfaces.

$\bf{U}_i = \bf{A} \bf{e}_i$  

$(19 \times 3) = (19 \times 4)(4 \times 3)$

Compute and print U. Be sure to normalize your eigenvectors `e` before using the above equation.

In [16]:
# YOUR CODE GOES HERE
e_normalized = e / np.linalg.norm(e, axis=0)
U = np.dot(A, e_normalized)
print("Eigenfaces, U:\n",U)

Eigenfaces, U:
 [[ 0.96647314  1.31269548  3.17691049]
 [-3.44941376  1.26029144 -1.12392626]
 [ 3.97467115 -1.02708294 -2.67340418]
 [-0.14144304  0.48500804  4.0920363 ]
 [ 3.66403602  1.87431665 -4.24991496]
 [-4.98467116 -1.61257473 -2.30274969]
 [-7.85142613  0.24219565 -0.54447132]
 [-2.63627584 -0.0396916  -2.40800213]
 [ 0.6054134  -0.77372912  1.94546084]
 [ 0.11179069 -2.77766199 -1.010988  ]
 [ 2.51061063  3.78304534 -1.46130156]
 [ 0.05042462  4.98782419 -0.34506112]
 [ 0.45699358  4.33783268 -0.98709906]
 [-0.69444948  2.18318305 -1.87121663]
 [ 2.56999436  0.08093747  1.54550254]
 [ 0.17608984  1.24447045  3.52424257]
 [ 0.67367721 -4.8783533  -0.86477055]
 [ 4.58008454 -1.80081206 -0.72794335]
 [ 2.14265314 -1.96424127 -0.5484467 ]]


## Projecting data into 3D

Now project your data into 3 dimensions with the formula: 

$\Omega = U^\text{T} A $  

$(3 \times 4) = (3 \times 19)(19 \times 4)$

Call the projected data $\Omega$ "`W`". Print `W.T`

In [17]:
# YOUR CODE GOES HERE
W = np.dot(U.T, A)
print('Projected data in 3 dimensions:\n',W.T)

Projected data in 3 dimensions:
 [[ -11.63579211    4.71510613  -79.89485976]
 [-138.75272415   -7.79928361   32.17398355]
 [  83.009453    -79.02022049   20.42175229]
 [  67.37906326   82.10439798   27.29912392]]


## Reconstructing data in 19-D

We can project the transformed data `W` back into the original 19-D space using:

$\Gamma_f = U \Omega + \Psi$   
where:  
$\Gamma_f = $ reconstructed data  
$U = $ eigenfaces  
$\Omega = $ Reduced data  
$\Psi = $ Means  

Do this, and compute the MSE between each reconstructed sample and corresponding original points. Report all 4 MSE values.




In [35]:
# YOUR CODE GOES HERE
Psi = np.mean(X, axis=0).reshape(-1, 1)
Gamma_f = np.dot(U, W) + Psi
mse = np.mean((X - Gamma_f.T) ** 2, axis=1)

for i in range(4):
    print("MSE for sample %d: %e" %(i+1,mse[i]))

MSE for sample 1: 1.371806e+03
MSE for sample 2: 1.762219e+05
MSE for sample 3: 9.985760e+04
MSE for sample 4: 8.132361e+04


## 2-D Reconstruction


What if we had only used the first 2 eigenvectors to compute the eigenfaces?
Below, redo the earlier calculations, but use only two eigenfaces. Compute the 4 MSE values that you would get in this case.

(You should get an MSE of 3.626 for the first sample.)

In [37]:
# YOUR CODE GOES HERE
e = eigenvectors[:, :2]
e_normalized = e / np.linalg.norm(e, axis=0)
U = np.dot(A, e_normalized)
U = U/np.linalg.norm(U, axis=0)

W = np.dot(U.T, A)

Psi = np.mean(X, axis=0).reshape(-1, 1)
Gamma_f = np.dot(U, W) + Psi
mse = np.mean((X - Gamma_f.T) ** 2, axis=1)

print("Using only 2 eigenvectors:")
for i in range(4):
    print("MSE for sample %d: %e" %(i+1,mse[i]))

Using only 2 eigenvectors:
MSE for sample 1: 3.626804e+00
MSE for sample 2: 5.881609e-01
MSE for sample 3: 2.369586e-01
MSE for sample 4: 4.234322e-01
